# Generated by Django 3.2.6 on 2021-09-09 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('eventDetails', models.TextField()),
                ('eventPosition', models.CharField(max_length=100)),
                ('eventUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('eventStartDate', models.DateTimeField()),
                ('eventEndDate', models.DateTimeField()),
                ('admin', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterFirstname', models.CharField(max_length=100)),
                ('voterLastname', models.CharField(max_length=100)),
                ('voterImg', models.ImageField(upload_to='pics')),
                ('voterFingerprint', models.IntegerField(unique=True)),
                ('admin', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.eventtable')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.votertable')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateFirstname', models.CharField(max_length=100)),
                ('candidateLastname', models.CharField(max_length=100)),
                ('candidateDetails', models.TextField()),
                ('candidateImg', models.ImageField(upload_to='pics')),
                ('admin', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.candidatetable')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.eventtable')),
            ],
        ),
    ]
