# Generated by Django 3.2.6 on 2021-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_eventtable_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidateevent',
            constraint=models.UniqueConstraint(fields=('candidate', 'event'), name='candidate_event'),
        ),
        migrations.AddConstraint(
            model_name='voterevent',
            constraint=models.UniqueConstraint(fields=('voter', 'event'), name='voter_event'),
        ),
    ]
