# Generated by Django 3.2.6 on 2021-09-02 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210902_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='eventEndDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtable',
            name='eventStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
