# Generated by Django 3.2.6 on 2021-09-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210904_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='userFingerprint',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
