# Generated by Django 3.2.6 on 2021-09-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_usertable_userfingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='userFingerprint',
            field=models.IntegerField(unique=True),
        ),
    ]
