# Generated by Django 3.2.6 on 2021-08-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.admin')),
            ],
        ),
    ]
